
development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: freemarket_sample_68b_development
  pool: 5
  username: root
  password: Sogen0921
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: freemarket_sample_68b_test
  pool: 5
  username: root
  password: Sogen0921
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: freemarket_sample_68b_production
  pool: 5
  username: root
  password: Sogen0921
  host: localhost